-- 方案一：采用多个表连接
SELECT TOP 999 A.SETT_DATE, A.SERIAL_NO, 
		case when A.BIZ_CODE in(20040054,20040187,20040191,20040195) then 'S' else 'D' end AS DIRECTION,
		A.OCCUR_DATE, SUBSTRING(CONVERT(CHAR(8),A.OCCUR_TIME,108),1,2)+SUBSTRING(CONVERT(CHAR(8),A.OCCUR_TIME,108),4,2)
		+SUBSTRING(CONVERT(CHAR(8),A.OCCUR_TIME,108),7,2) AS OPERTIME,
		A.USER_CODE, A.INT_ORG, A.CUACCT_CODE, U.USER_NAME, A.LEDGER_SN, B.LEDGER_NAME, C.LEDGER_SN, A.CURRENCY, ''AS MARKET,
		'' AS SECUID, '' AS STK_CODE, '' AS STK_NAME,'0' AS OPERTYPE,'0' AS TRANS_TYPE,A.BIZ_AMT,0 as STK_EFFECT,'1' AS STATUS
  FROM V_HIS_CUACCT_LEDGER_LOG A
  LEFT JOIN CUACCT_CURRENCY_LEDGER B ON A.CUACCT_CODE = B.CUACCT_CODE AND A.CURRENCY = B.CURRENCY AND A.LEDGER_SN = B.LEDGER_SN
  LEFT JOIN USERS U ON  A.USER_CODE = U.USER_CODE 
  LEFT JOIN V_HIS_CUACCT_LEDGER_LOG C ON A.BIZ_NO = C.BIZ_NO AND A.SERIAL_NO != C.SERIAL_NO
 WHERE 1=1 


 -- 方案二： 扩展表字段，减少了表的连接数量
 SELECT TOP 999 A.SETT_DATE, A.SERIAL_NO, 
		case when A.BIZ_CODE in(20040054,20040187,20040191,20040195) then 'S' else 'D' end AS DIRECTION,
		A.OCCUR_DATE, SUBSTRING(CONVERT(CHAR(8),A.OCCUR_TIME,108),1,2)+SUBSTRING(CONVERT(CHAR(8),A.OCCUR_TIME,108),4,2)
		+SUBSTRING(CONVERT(CHAR(8),A.OCCUR_TIME,108),7,2) AS OPERTIME,
		A.USER_CODE, A.INT_ORG, A.CUACCT_CODE, A.USER_NAME, A.LEDGER_SN, A.LEDGER_NAME, B.LEDGER_SN, A.CURRENCY, ''AS MARKET,
		'' AS SECUID, '' AS STK_CODE, '' AS STK_NAME,'0' AS OPERTYPE,'0' AS TRANS_TYPE,A.BIZ_AMT,0 as STK_EFFECT,'1' AS STATUS
  FROM V_HIS_CUACCT_LEDGER_LOG A
  LEFT JOIN CUACCT_LEDGER_LOG B ON A.BIZ_NO = B.BIZ_NO AND A.SERIAL_NO != B.SERIAL_NO
  WHERE 1=1 

 --方案三：使用子查询，缩小连接表的大小
SELECT SETT_DATE,A.BIZ_NO,A.SERIAL_NO,BIZ_CODE,DIRECTION,OCCUR_DATE,OPERTIME,USER_CODE,CUST_NAME,
		INT_ORG,CUACCT_CODE,A.LEDGER_SN,A.LEDGER_NAME,COALESCE(B.LEDGER_SN,'') AS OTHER_LEDGER_SN, 
		COALESCE(B.LEDGER_NAME,'') AS OTHER_LEDGER_NAME,CURRENCY,MARKET,SECUID, STK_CODE, STK_NAME, 
		OPERTYPE,TRANS_TYPE,BIZ_AMT,STK_EFFECT,STATUS 
FROM 
	(SELECT TOP 100 SETT_DATE,BIZ_NO,SERIAL_NO,BIZ_CODE,case when BIZ_CODE = 20040054 then 'S' else 'D' end 
			AS DIRECTION,OCCUR_DATE, SUBSTRING(CONVERT(CHAR(8),OCCUR_TIME,108),1,2)+SUBSTRING(CONVERT(CHAR(8)
			,OCCUR_TIME,108),4,2)+SUBSTRING(CONVERT(CHAR(8),OCCUR_TIME,108),7,2) AS OPERTIME, A.USER_CODE,
			USER_NAME AS CUST_NAME,A.INT_ORG,A.CUACCT_CODE,A.LEDGER_SN,LEDGER_NAME,'' AS OTHER_LEDGER_SN,
			'' AS OTHER_LEDGER_NAME,A.CURRENCY,''AS MARKET, '' AS SECUID, '' AS STK_CODE, '' AS STK_NAME,
			'0' AS OPERTYPE,'0' AS TRANS_TYPE,BIZ_AMT,0 as STK_EFFECT,'1' AS STATUS 
	  FROM V_HIS_CUACCT_LEDGER_LOG A 
	 WHERE 1=1 
	 ORDER BY SERIAL_NO  
	 ) A
  LEFT JOIN
	(SELECT BIZ_NO,SERIAL_NO,LEDGER_SN,LEDGER_NAME 
	   FROM V_HIS_CUACCT_LEDGER_LOG A  
	  WHERE 1=1 
	 ) B
ON A.BIZ_NO = B.BIZ_NO AND A.SERIAL_NO != B.SERIAL_NO